### ISSUE TITLE
Error while running the ipynb file

### ISSUE THREAD

**Issue by gokuljs** [Pythonista7/SIR-Modeling-Covid-in-Bangalore#1]
![Screenshot (154)](https://user-images.githubusercontent.com/51263906/97948689-52c82080-1db7-11eb-956c-929ec05d2e41.png)

**Comment by gokuljs** [comment]
![Screenshot (153)](https://user-images.githubusercontent.com/51263906/97948735-6bd0d180-1db7-11eb-9cb9-99e7dbee7984.png)

**Comment by Pythonista7** [comment]
Can you try uncommenting the cell-46 (just above the section titled - "Now let us try combine this with geographical data and plot it on a map") as per the original ipynb file in the repo. I think that should solve the issue.

**Comment by gokuljs** [comment]
Not its not working so when I commented out cell number 46 time-series not initialized an error is occurring

**Comment by gokuljs** [comment]
sorted
